kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: node:13
    commands:
      - yarn install

  - name: linter
    image: node:13
    commands:
      - make eslint

  - name: ls-lint
    image: node:13
    commands:
      - make ls-lint

  - name: build
    image: node:13
    commands:
      - yarn prod
